name: Run linux commands
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      -name: execute linux commands
       run: echo "hello all"
  job2: 
    runs-on: ubuntu-24.04
      -name : set of commands
      run:
         hostname 
         echo "thank you all"
